spring:
  main:
    allow-circular-references: true
  application:
    name: social-networking-kata
  profiles:
    #    active: dev @activeProfile@
    default: "none"
  batch:    initialize-schema: ALWAYS
  datasource:
    platform: h2
    url: jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    initialization-mode: always
    continue-on-error: false

    